import type { RouteSpec } from './types';

export const routeRegistry: RouteSpec[] = [
  {
    routeId: 'assets.tokens',
    kind: 'asset',
    path: '/assets/tokens',
    title: 'Token Management',
    componentKey: 'AssetTokenDocumentationPage',
    nav: {
      visible: true,
      group: 'Assets',
      label: 'Tokens',
      iconKey: 'palette',
      order: 10,
    },
    endpoints: [
      {
        id: 'tokens.docs',
        method: 'GET',
        path: '/api/assets/tokens/docs',
        description: 'Returns token management guidance rendered by the documentation route.',
      },
    ],
    mock: {
      seed: 11,
      latencyMs: 120,
      errorRate: 0,
    },
  },
  {
    routeId: 'assets.tokens.semantic',
    kind: 'asset',
    path: '/assets/tokens/semantic',
    title: 'Tokens - Semantic',
    componentKey: 'AssetTokensPage',
    nav: {
      visible: false,
      group: 'Assets',
      label: 'Semantic',
      iconKey: 'palette',
      order: 11,
    },
    endpoints: [
      {
        id: 'tokens.semantic.list',
        method: 'GET',
        path: '/api/assets/tokens/semantic',
        description: 'Returns semantic token groups and metadata for the token explorer route.',
      },
    ],
    mock: {
      seed: 11,
      latencyMs: 120,
      errorRate: 0,
    },
  },
  {
    routeId: 'assets.tokens.base',
    kind: 'asset',
    path: '/assets/tokens/base',
    title: 'Tokens - Base',
    componentKey: 'AssetTokensPage',
    nav: {
      visible: false,
      group: 'Assets',
      label: 'Base',
      iconKey: 'palette',
      order: 12,
    },
    endpoints: [
      {
        id: 'tokens.base.list',
        method: 'GET',
        path: '/api/assets/tokens/base',
        description: 'Returns base token groups and metadata for the token explorer route.',
      },
    ],
    mock: {
      seed: 11,
      latencyMs: 120,
      errorRate: 0,
    },
  },
  {
    routeId: 'assets.icons',
    kind: 'asset',
    path: '/assets/icons',
    title: 'Icons',
    componentKey: 'AssetIconsPage',
    nav: {
      visible: true,
      group: 'Assets',
      label: 'Icons',
      iconKey: 'imagesmode',
      order: 20,
    },
    endpoints: [
      {
        id: 'icons.list',
        method: 'GET',
        path: '/api/assets/icons',
        description: 'Returns icon names and categories for the icon explorer route.',
      },
    ],
    mock: {
      seed: 12,
      latencyMs: 120,
      errorRate: 0,
    },
  },
  {
    routeId: 'assets.typography',
    kind: 'asset',
    path: '/assets/typography',
    title: 'Typography',
    componentKey: 'AssetTypographyPage',
    nav: {
      visible: true,
      group: 'Assets',
      label: 'Typography',
      iconKey: 'format_size',
      order: 30,
    },
    endpoints: [
      {
        id: 'typography.list',
        method: 'GET',
        path: '/api/assets/typography',
        description: 'Returns typography scale samples and token references.',
      },
    ],
    mock: {
      seed: 13,
      latencyMs: 120,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.dashboard',
    kind: 'view',
    path: '/views/dashboard',
    title: 'Dashboard',
    componentKey: 'DashboardViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Dashboard',
      iconKey: 'monitoring',
      order: 10,
    },
    viewPatternId: 'dashboard',
    endpoints: [
      {
        id: 'widgets.list',
        method: 'GET',
        path: '/api/widgets',
        description: 'KPI cards and dashboard widget metrics.',
      },
      {
        id: 'analytics.summary',
        method: 'GET',
        path: '/api/analytics/summary',
        description: 'Aggregated analytics backing EChart dashboard visualizations.',
      },
    ],
    mock: {
      seed: 21,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.table',
    kind: 'view',
    path: '/views/table',
    title: 'Table',
    componentKey: 'TableViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Table',
      iconKey: 'table_view',
      order: 20,
    },
    viewPatternId: 'table',
    endpoints: [
      {
        id: 'objects.list',
        method: 'GET',
        path: '/api/objects',
        description: 'Returns account rows used by the full table experience.',
      },
      {
        id: 'objects.filters',
        method: 'GET',
        path: '/api/objects/filters',
        description: 'Returns filter and column configuration metadata.',
      },
    ],
    mock: {
      seed: 22,
      latencyMs: 360,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.card',
    kind: 'view',
    path: '/views/card/classic',
    title: 'Card View',
    componentKey: 'CardViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Card View',
      iconKey: 'grid_view',
      order: 30,
    },
    endpoints: [
      {
        id: 'cards.list',
        method: 'GET',
        path: '/api/cards',
        description: 'Returns card-oriented record payloads for collection browsing.',
      },
    ],
    mock: {
      seed: 23,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.card.projectOverview',
    kind: 'view',
    path: '/views/card/project-overview',
    title: 'Card View - Project Overview',
    componentKey: 'CardViewDemoRoute',
    nav: {
      visible: false,
      group: 'Views',
      label: 'Project Overview',
      iconKey: 'description',
      order: 31,
    },
    endpoints: [
      {
        id: 'cards.list',
        method: 'GET',
        path: '/api/cards',
        description: 'Returns card-oriented record payloads for collection browsing.',
      },
    ],
    mock: {
      seed: 23,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.card.toolRegistry',
    kind: 'view',
    path: '/views/card/tool-registry',
    title: 'Card View - Tool Registry',
    componentKey: 'CardViewDemoRoute',
    nav: {
      visible: false,
      group: 'Views',
      label: 'Tool Registry',
      iconKey: 'build',
      order: 32,
    },
    endpoints: [
      {
        id: 'cards.list',
        method: 'GET',
        path: '/api/cards',
        description: 'Returns card-oriented record payloads for collection browsing.',
      },
    ],
    mock: {
      seed: 23,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.card.platformComponent',
    kind: 'view',
    path: '/views/card/platform-component',
    title: 'Card View - Platform Component',
    componentKey: 'CardViewDemoRoute',
    nav: {
      visible: false,
      group: 'Views',
      label: 'Platform Component',
      iconKey: 'widgets',
      order: 33,
    },
    endpoints: [
      {
        id: 'cards.list',
        method: 'GET',
        path: '/api/cards',
        description: 'Returns card-oriented record payloads for collection browsing.',
      },
    ],
    mock: {
      seed: 23,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.card.spotlight',
    kind: 'view',
    path: '/views/card/spotlight',
    title: 'Card View - Spotlight',
    componentKey: 'CardViewDemoRoute',
    nav: {
      visible: false,
      group: 'Views',
      label: 'Spotlight',
      iconKey: 'star',
      order: 34,
    },
    endpoints: [
      {
        id: 'cards.list',
        method: 'GET',
        path: '/api/cards',
        description: 'Returns card-oriented record payloads for collection browsing.',
      },
    ],
    mock: {
      seed: 23,
      latencyMs: 280,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.users',
    kind: 'view',
    path: '/views/users',
    title: 'Users',
    componentKey: 'UsersViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Users',
      iconKey: 'group',
      order: 25,
    },
    endpoints: [],
    mock: {
      seed: 27,
      latencyMs: 200,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.aiHome',
    kind: 'view',
    path: '/views/ai-home',
    title: 'AI Assist Home',
    componentKey: 'AIAssistHomeDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Home',
      iconKey: 'auto_awesome',
      order: 1,
    },
  },
  {
    routeId: 'views.chat',
    kind: 'view',
    path: '/views/chat',
    title: 'Chat',
    componentKey: 'ChatViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Chat',
      iconKey: 'chat',
      order: 45,
    },
    endpoints: [
      {
        id: 'chat.conversations',
        method: 'GET',
        path: '/api/chat/conversations',
        description: 'Returns chat threads used by the conversation rail.',
      },
      {
        id: 'chat.completions',
        method: 'POST',
        path: '/api/chat/completions',
        description: 'Returns assistant responses for the current prompt and selected thread.',
      },
    ],
    mock: {
      seed: 26,
      latencyMs: 320,
      errorRate: 0,
    },
  },
  {
    routeId: 'views.objectDetails',
    kind: 'view',
    path: '/views/object/:objectId',
    title: 'Object Details',
    componentKey: 'ObjectDetailsViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Object View',
      iconKey: 'description',
      order: 50,
    },
    viewPatternId: 'details',
    params: [
      {
        name: 'objectId',
        type: 'string',
        required: true,
      },
    ],
    endpoints: [
      {
        id: 'objects.getById',
        method: 'GET',
        path: '/api/objects/:objectId',
        description: 'Returns object details by objectId.',
      },
    ],
    mock: {
      seed: 24,
      latencyMs: 300,
      errorRate: 0.05,
    },
  },
  {
    routeId: 'views.flow',
    kind: 'view',
    path: '/views/flow/:flowId',
    title: 'Flow',
    componentKey: 'FlowViewDemoRoute',
    nav: {
      visible: true,
      group: 'Views',
      label: 'Flow',
      iconKey: 'account_tree',
      order: 40,
    },
    viewPatternId: 'flow',
    params: [
      {
        name: 'flowId',
        type: 'string',
        required: true,
      },
    ],
    endpoints: [
      {
        id: 'flows.getById',
        method: 'GET',
        path: '/api/flows/:flowId',
        description: 'Returns flow topology and node metadata by flowId.',
      },
    ],
    mock: {
      seed: 25,
      latencyMs: 340,
      errorRate: 0,
    },
  },
];
