import type { SideNavItem } from '@uniphore/ut-design-system';

export const NAV_ITEMS: SideNavItem[] = [
  // Insights
  {
    id: 'analytics',
    text: 'Analytics',
    icon: 'insights',
    groupId: 'insights',
    groupName: 'Insights',
    active: false,
    tooltip: 'Analytics',
    roles: [],
    routeName: '/analytics',
  },
  {
    id: 'reports',
    text: 'Reports',
    icon: 'reports',
    groupId: 'insights',
    groupName: 'Insights',
    active: false,
    tooltip: 'Reports',
    roles: [],
    routeName: '/reports',
  },
  {
    id: 'benchmarks',
    text: 'Benchmarks',
    icon: 'benchmarks',
    groupId: 'insights',
    groupName: 'Insights',
    active: false,
    tooltip: 'Benchmarks',
    roles: [],
    routeName: '/benchmarks',
  },

  // Contact Center Suite
  {
    id: 'copilot',
    text: 'Co-Pilot',
    icon: 'agents',
    groupId: 'applications',
    groupName: 'Contact Center Suite',
    active: false,
    tooltip: 'Co-Pilot',
    roles: [],
    routeName: '/copilot',
  },
  {
    id: 'process-discovery',
    text: 'Process Discovery',
    icon: 'deploy',
    groupId: 'applications',
    groupName: 'Contact Center Suite',
    active: false,
    tooltip: 'Process Discovery',
    roles: [],
    routeName: '/process-discovery',
  },
  {
    id: 'agent-studio',
    text: 'Agent Studio',
    icon: 'studio',
    groupId: 'applications',
    groupName: 'Contact Center Suite',
    active: false,
    tooltip: 'Agent Studio',
    roles: [],
    routeName: '/agent-studio',
  },
  {
    id: 'self-serve',
    text: 'Self Serve',
    icon: 'channels',
    groupId: 'applications',
    groupName: 'Contact Center Suite',
    active: false,
    tooltip: 'Self Serve',
    roles: [],
    routeName: '/self-serve',
  },
  {
    id: 'answers',
    text: 'Answers',
    icon: 'skills',
    groupId: 'applications',
    groupName: 'Contact Center Suite',
    active: false,
    tooltip: 'Answers',
    roles: [],
    routeName: '/answers',
  },

  // Cloud Platform
  {
    id: 'knowledge',
    text: 'Knowledge',
    icon: 'knowledge',
    groupId: 'services',
    groupName: 'Cloud Platform',
    active: false,
    tooltip: 'Knowledge',
    roles: [],
    routeName: '/knowledge',
  },
  {
    id: 'models',
    text: 'Models',
    icon: 'models',
    groupId: 'services',
    groupName: 'Cloud Platform',
    active: false,
    tooltip: 'Models',
    roles: [],
    routeName: '/models',
  },
  {
    id: 'agents-nav',
    text: 'Agents',
    icon: 'agents',
    groupId: 'services',
    groupName: 'Cloud Platform',
    active: false,
    tooltip: 'Agents',
    roles: [],
    routeName: '/agents',
  },
  {
    id: 'data-nav',
    text: 'Data',
    icon: 'data',
    groupId: 'services',
    groupName: 'Cloud Platform',
    active: false,
    tooltip: 'Data',
    roles: [],
    routeName: '/data',
  },

  // Administration
  {
    id: 'tenants',
    text: 'Tenants',
    icon: 'admin',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Tenants',
    roles: [],
    routeName: '/tenants',
  },
  {
    id: 'users',
    text: 'User Management',
    icon: 'users',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'User Management',
    roles: [],
    routeName: '/users',
  },
  {
    id: 'integrations',
    text: 'Integrations',
    icon: 'integrations',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Integrations',
    roles: [],
    routeName: '/integrations',
  },
  {
    id: 'system-settings',
    text: 'System Settings',
    icon: 'compliance',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'System Settings',
    roles: [],
    routeName: '/system-settings',
  },
  {
    id: 'configurations',
    text: 'Configurations',
    icon: 'health',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Configurations',
    roles: [],
    routeName: '/configurations',
  },
  {
    id: 'api-console',
    text: 'API Console',
    icon: 'cloud',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'API Console',
    roles: [],
    routeName: '/api-console',
  },
  {
    id: 'knowledge-base',
    text: 'Knowledge Base',
    icon: 'knowledge',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Knowledge Base',
    roles: [],
    routeName: '/knowledge-base',
  },
  {
    id: 'billing',
    text: 'Billing',
    icon: 'data',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Billing',
    roles: [],
    routeName: '/billing',
  },
  {
    id: 'audit-logs',
    text: 'Audit Logs',
    icon: 'compliance',
    groupId: 'configuration',
    groupName: 'Administration',
    active: false,
    tooltip: 'Audit Logs',
    roles: [],
    routeName: '/audit-logs',
  },
];
